# <center> Text Generation - Next Word Prediction

In [1]:

import numpy as np # linear algebra
import pandas as pd 



## 1. Functions for Processing Text

### a. Reading in files as a string text

In [2]:
def read_file(filepath):
    
    with open(filepath,encoding='utf8') as f:
        str_text = f.read()
    
    return str_text

In [3]:
file1=open('1661-0.txt', encoding='utf-8')

In [4]:
len("aditi")

5

In [5]:
print(read_file('1661-0.txt')[:5000])


Project Gutenberg's The Adventures of Sherlock Holmes, by Arthur Conan Doyle

This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  You may copy it, give it away or
re-use it under the terms of the Project Gutenberg License included
with this eBook or online at www.gutenberg.net


Title: The Adventures of Sherlock Holmes

Author: Arthur Conan Doyle

Release Date: November 29, 2002 [EBook #1661]
Last Updated: May 20, 2019

Language: English

Character set encoding: UTF-8

*** START OF THIS PROJECT GUTENBERG EBOOK THE ADVENTURES OF SHERLOCK HOLMES ***



Produced by an anonymous Project Gutenberg volunteer and Jose Menendez



cover



The Adventures of Sherlock Holmes



by Arthur Conan Doyle



Contents


   I.     A Scandal in Bohemia
   II.    The Red-Headed League
   III.   A Case of Identity
   IV.    The Boscombe Valley Mystery
   V.     The Five Orange Pips
   VI.    The Man with the Twisted Lip
   VII.   The Adventure of the Blue C

### b. Tokenize and Clean Text

In [6]:
import spacy
import en_core_web_sm

nlp = en_core_web_sm.load()
nlp.max_length = 1198623

C:\Anaconda\lib\site-packages\spacy\util.py:275: UserWarning: [W031] Model 'en_core_web_sm' (2.2.5) requires spaCy v2.2 and is incompatible with the current spaCy version (2.3.7). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)


In [11]:
def read_file(filepath):
    
    with open(filepath,encoding='utf8') as f:
        str_text = f.read()
    
    return str_text[:250000]

In [12]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [13]:
d = read_file('1661-0.txt')
tokens = separate_punc(d)

In [14]:
type(tokens)

list

In [15]:
len(tokens)

49680

In [16]:
tokens[:10]

['\ufeff',
 'project',
 'gutenberg',
 "'s",
 'the',
 'adventures',
 'of',
 'sherlock',
 'holmes',
 'by']

### c. Create Sequences of Tokens

In [17]:
# organize into sequences of tokens
train_len = 25+1 # 25 training words , then one target word

# Empty list of sequences
text_sequences = []

for i in range(train_len, len(tokens)):
    
    # Grab train_len# amount of characters
    seq = tokens[i-train_len:i]
    
    # Add to list of sequences
    text_sequences.append(seq)

In [19]:
print(read_file('1661-0.txt')[:1000])


Project Gutenberg's The Adventures of Sherlock Holmes, by Arthur Conan Doyle

This eBook is for the use of anyone anywhere at no cost and with
almost no restrictions whatsoever.  You may copy it, give it away or
re-use it under the terms of the Project Gutenberg License included
with this eBook or online at www.gutenberg.net


Title: The Adventures of Sherlock Holmes

Author: Arthur Conan Doyle

Release Date: November 29, 2002 [EBook #1661]
Last Updated: May 20, 2019

Language: English

Character set encoding: UTF-8

*** START OF THIS PROJECT GUTENBERG EBOOK THE ADVENTURES OF SHERLOCK HOLMES ***



Produced by an anonymous Project Gutenberg volunteer and Jose Menendez



cover



The Adventures of Sherlock Holmes



by Arthur Conan Doyle



Contents


   I.     A Scandal in Bohemia
   II.    The Red-Headed League
   III.   A Case of Identity
   IV.    The Boscombe Valley Mystery
   V.     The Five Orange Pips
   VI.    The Man with the Twisted Lip
   VII.   The Adventure of the Blue 


In [20]:
' '.join(text_sequences[0])

"\ufeff project gutenberg 's the adventures of sherlock holmes by arthur conan doyle this ebook is for the use of anyone anywhere at no cost and"

In [21]:
' '.join(text_sequences[1])

"project gutenberg 's the adventures of sherlock holmes by arthur conan doyle this ebook is for the use of anyone anywhere at no cost and with"

In [22]:
' '.join(text_sequences[2])

"gutenberg 's the adventures of sherlock holmes by arthur conan doyle this ebook is for the use of anyone anywhere at no cost and with almost"

In [23]:
len(text_sequences) #Every sentence is containing 26 words

49654

In [24]:
len(tokens) # These are total number of words in the whole novel

49680

In [25]:
print(len(text_sequences[0]))
print(text_sequences[0])

26
['\ufeff', 'project', 'gutenberg', "'s", 'the', 'adventures', 'of', 'sherlock', 'holmes', 'by', 'arthur', 'conan', 'doyle', 'this', 'ebook', 'is', 'for', 'the', 'use', 'of', 'anyone', 'anywhere', 'at', 'no', 'cost', 'and']


### d. Keras Tokenization

In [26]:
from keras.preprocessing.text import Tokenizer

In [27]:
# integer encode sequences of words
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

In [28]:
print(len(sequences[0]))
print(sequences[0])

26
[5404, 1350, 1349, 5403, 1, 786, 3, 110, 31, 46, 1801, 1800, 1799, 36, 1348, 16, 24, 1, 267, 3, 688, 2658, 23, 47, 1798, 2]


In [29]:
type(tokenizer.index_word)

dict

In [30]:
' '.join(text_sequences[0])

"\ufeff project gutenberg 's the adventures of sherlock holmes by arthur conan doyle this ebook is for the use of anyone anywhere at no cost and"

In [31]:
i=0
for a in tokenizer.index_word:
    print(a,"--->",tokenizer.index_word[a])
    i+=1
    if i==20 : break 

1 ---> the
2 ---> and
3 ---> of
4 ---> to
5 ---> i
6 ---> “
7 ---> a
8 ---> ”
9 ---> in
10 ---> it
11 ---> that
12 ---> he
13 ---> was
14 ---> you
15 ---> his
16 ---> is
17 ---> as
18 ---> have
19 ---> with
20 ---> my


In [ ]:
for i in sequences[0]:
    print(f'{i} : {tokenizer.index_word[i]}')

187 : chapter
7000 : 1
6999 : loomings
516 : call
24 : me
432 : ishmael
65 : some
232 : years
640 : ago
100 : never
223 : mind
99 : how
93 : long
1331 : precisely
277 : having
68 : little
48 : or
36 : no
639 : money
6 : in
31 : my
1028 : purse
2 : and
150 : nothing
431 : particular
5 : to


In [32]:
i=0
for a in tokenizer.word_counts:
    print((a,tokenizer.word_counts[a]))
    i+=1
    if i==10 : break 

('\ufeff', 1)
('project', 80)
('gutenberg', 81)
("'s", 4)
('the', 66141)
('adventures', 162)
('of', 32405)
('sherlock', 1412)
('holmes', 5911)
('by', 4196)


In [33]:
vocabulary_size = len(tokenizer.word_counts)
vocabulary_size

5404

In [37]:
i=5300
for a in range(i,5400):
    print(a,"--->",tokenizer.index_word[a])
    #i+=1
    #if i==6999 : break 

5300 ---> expecting
5301 ---> aberdeen
5302 ---> shipping
5303 ---> shopping
5304 ---> proceeded
5305 ---> 4:35
5306 ---> ejaculation
5307 ---> describes
5308 ---> agitated
5309 ---> frantically
5310 ---> plucked
5311 ---> irresistible
5312 ---> feminine
5313 ---> necktie
5314 ---> attempted
5315 ---> ascend
5316 ---> aided
5317 ---> dane
5318 ---> acts
5319 ---> fears
5320 ---> constables
5321 ---> accompanied
5322 ---> resistance
5323 ---> crippled
5324 ---> wretch
5325 ---> aspect
5326 ---> stoutly
5327 ---> denial
5328 ---> deluded
5329 ---> cascade
5330 ---> toy
5331 ---> discovery
5332 ---> abominable
5333 ---> strip
5334 ---> windowsill
5335 ---> drops
5336 ---> curtain
5337 ---> socks
5338 ---> exit
5339 ---> bloodstains
5340 ---> sill
5341 ---> swimming
5342 ---> villains
5343 ---> implicated
5344 ---> antecedents
5345 ---> accessory
5346 ---> defence
5347 ---> protested
5348 ---> beggar
5349 ---> regulations
5350 ---> pretends
5351 ---> vestas
5352 ---> threadneedle
5353 --->

In [ ]:
# tokenizer.index_word

### e. Convert to Numpy Matrix

In [38]:
import numpy as np

In [39]:
len(sequences)

49654

In [40]:
len(sequences[0])

26

In [41]:
sequences = np.array(sequences)

In [42]:
sequences.shape

(49654, 26)

In [43]:
sequences

array([[5404, 1350, 1349, ...,   47, 1798,    2],
       [1350, 1349, 5403, ..., 1798,    2,   19],
       [1349, 5403,    1, ...,    2,   19,  472],
       ...,
       [  87,  206, 1791, ...,   59,   10,   51],
       [ 206, 1791,    3, ...,   10,   51, 1351],
       [1791,    3,    1, ...,   51, 1351,    4]])

## 2. Creating an LSTM based model

In [44]:
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [45]:
def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, 25, input_length=seq_len))
    model.add(LSTM(150, return_sequences=True))
    model.add(LSTM(150))
    model.add(Dense(150, activation='relu'))

    model.add(Dense(vocabulary_size, activation='softmax'))
    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
   
    model.summary()
    
    return model

## 3. Train / Test Split

In [46]:
from tensorflow.keras.utils import to_categorical

In [47]:
print(sequences.shape)
sequences

(49654, 26)


array([[5404, 1350, 1349, ...,   47, 1798,    2],
       [1350, 1349, 5403, ..., 1798,    2,   19],
       [1349, 5403,    1, ...,    2,   19,  472],
       ...,
       [  87,  206, 1791, ...,   59,   10,   51],
       [ 206, 1791,    3, ...,   10,   51, 1351],
       [1791,    3,    1, ...,   51, 1351,    4]])

In [48]:
# First 25 words
print(sequences[:,:-1].shape)
sequences[:,:-1]

(49654, 25)


array([[5404, 1350, 1349, ...,   23,   47, 1798],
       [1350, 1349, 5403, ...,   47, 1798,    2],
       [1349, 5403,    1, ..., 1798,    2,   19],
       ...,
       [  87,  206, 1791, ...,   60,   59,   10],
       [ 206, 1791,    3, ...,   59,   10,   51],
       [1791,    3,    1, ...,   10,   51, 1351]])

In [49]:
# last Word
print(sequences[:,-1].shape)
sequences[:,-1]

(49654,)


array([   2,   19,  472, ...,   51, 1351,    4])

In [50]:
X = sequences[:,:-1]

In [51]:
X.shape

(49654, 25)

In [52]:
y = sequences[:,-1]

In [53]:
y.shape

(49654,)

In [54]:
y = to_categorical(y, num_classes=vocabulary_size)

In [55]:
y.shape

(49654, 5404)

In [56]:
seq_len = X.shape[1]

In [57]:
seq_len

25

## 4. Training the Model

In [58]:
# define model
model = create_model(vocabulary_size, seq_len)
#model = create_model(vocabulary_size, seq_len)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 25, 25)            135100    
_________________________________________________________________
lstm (LSTM)                  (None, 25, 150)           105600    
_________________________________________________________________
lstm_1 (LSTM)                (None, 150)               180600    
_________________________________________________________________
dense (Dense)                (None, 150)               22650     
_________________________________________________________________
dense_1 (Dense)              (None, 5404)              816004    
Total params: 1,259,954
Trainable params: 1,259,954
Non-trainable params: 0
_________________________________________________________________


---

----

## 5. Fit model

In [61]:
model.fit(X, y, batch_size=64, epochs=70,verbose=1,validation_batch_size=0.20)

Epoch 1/70
263/776 [=========>....................] - ETA: 2:17 - loss: 6.3715 - accuracy: 0.0532

InvalidArgumentError:  indices[5,0] = 5404 is not in [0, 5404)
	 [[node sequential/embedding/embedding_lookup (defined at <ipython-input-59-d0529b312f9a>:1) ]] [Op:__inference_train_function_5655]

Errors may have originated from an input operation.
Input Source operations connected to node sequential/embedding/embedding_lookup:
 sequential/embedding/embedding_lookup/3452 (defined at C:\Anaconda\lib\contextlib.py:113)

Function call stack:
train_function


### Download Model Object

In [ ]:
from pickle import dump,load

In [ ]:
# save the model to file
model.save('epochBIG.h5')
# save the tokenizer
dump(tokenizer, open('epochBIG', 'wb'))

## 6. Generating New Text

In [ ]:
from random import randint
from pickle import load
from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences

In [ ]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''
    
    # Final Output
    output_text = []
    
    # Intial Seed Sequence
    input_text = seed_text
    
    # Create num_gen_words
    for i in range(num_gen_words):
        
        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        # Pad sequences to our trained rate (25 words in the video)
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
        
        # Predict Class Probabilities for each word
        #pred_word_ind = model.predict_classes(pad_encoded, verbose=0)[0]
        predict_x=model.predict(pad_encoded) 
        pred_word_ind=np.argmax(predict_x,axis=1)[0]
        #print(pred_word_ind)
        # Grab word
        pred_word = tokenizer.index_word[pred_word_ind] 
        
        # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
        
    # Make it look like a sentence.
    return ' '.join(output_text)

## 7. Grab a random Text Sequence

In [ ]:
print(text_sequences[0])

['chapter', '1', 'loomings', 'call', 'me', 'ishmael', 'some', 'years', 'ago', 'never', 'mind', 'how', 'long', 'precisely', 'having', 'little', 'or', 'no', 'money', 'in', 'my', 'purse', 'and', 'nothing', 'particular', 'to']


In [ ]:
import random
random_pick = random.randint(0,len(text_sequences))

In [ ]:
random_seed_text = text_sequences[random_pick]

In [ ]:
print(random_seed_text)

['events', 'soberly', 'recurred', 'one', 'by', 'one', 'in', 'fixed', 'reality', 'and', 'then', 'i', 'lay', 'only', 'alive', 'to', 'the', 'comical', 'predicament', 'for', 'though', 'i', 'tried', 'to', 'move', 'his']


In [ ]:
seed_text = ' '.join(random_seed_text)
seed_text

'events soberly recurred one by one in fixed reality and then i lay only alive to the comical predicament for though i tried to move his'

In [ ]:
model = load_model('epochBIG.h5')

In [ ]:
tokenizer = load(open('epochBIG', 'rb'))

In [ ]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=3)

'arm unlock his'

In [ ]:
text=' It is a way I have of driving off the spleen and regulating the circulation.  Whenever I find'
print(text)

 It is a way I have of driving off the spleen and regulating the circulation.  Whenever I find


In [ ]:
generate_text(model,tokenizer,seq_len,seed_text=text,num_gen_words=3)

'myself growing grim'

In [ ]:
print(read_file('/kaggle/input/nlp-specialization-data/Novel - Moby-Dick By Herman Melville.txt')[250000:251000])

f the crew, were a far more barbaric, heathenish, and
motley set than any of the tame merchant-ship companies which my
previous experiences had made me acquainted with, still I ascribed
this--and rightly ascribed it--to the fierce uniqueness of the very
nature of that wild Scandinavian vocation in which I had so
abandonedly embarked.  But it was especially the aspect of the three
chief officers of the ship, the mates, which was most forcibly
calculated to allay these colourless misgivings, and induce confidence
and cheerfulness in every presentment of the voyage.  Three better,
more likely sea-officers and men, each in his own different way,
could not readily be found, and they were every one of them
Americans; a Nantucketer, a Vineyarder, a Cape man.  Now, it being
Christmas when the ship shot from out her harbor, for a space we had
biting Polar weather, though all the time running away from it to the
southward; and by every degree and minute of latitude which we
sailed, gradually lea

In [ ]:
test_text='Three better,more likely sea-officers and men, each in his own different way,could not readily be found, and they were every'
print(test_text)

Three better,more likely sea-officers and men, each in his own different way,could not readily be found, and they were every


In [ ]:
generate_text(model,tokenizer,seq_len,seed_text=test_text,num_gen_words=1)

'god'

In [ ]:
seed_text = "landsman has had fresh fruit to his daily hand and broken the world 's fresh bread to my mouldy crusts away whole oceans away from that"

In [ ]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=3)